=== Chtejasrinivas/web/Web_Technologies_lab/XML/student.dtd
<!ELEMENT student (student-info*)>
<!ELEMENT student-info (name,rollno,address)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name gender CDATA 'Male'>
<!ATTLIST name gender (M|F) "M">
<!ELEMENT rollno (#PCDATA)>
<!ELEMENT address (city,contact-no)>
<!ELEMENT city (#PCDATA)>
<!ATTLIST city pin CDATA #IMPLIED>
<!ELEMENT contact-no (#PCDATA)>

=== Chtejasrinivas/web/Web_Technologies_lab/XML/internal-DTD-example.xml
<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE student SYSTEM "student.dtd">
<student>
<student-info>
<name gender="M"> Teja Srinivas</name>
<rollno>16</rollno>
<address>
<city pin="522019">Cowdavaram</city>
<contact-no>756542</contact-no>
</address>
</student-info>
<student-info>
<name gender="M">Harsha</name>
<rollno>62</rollno>
<address>
<city pin="522001">Mumbai</city>
<contact-no>3129</contact-no>
</address>
</student-info>
</student>
